<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0-windows</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <UseWPF>true</UseWPF>
    <UseWindowsForms>true</UseWindowsForms>
    <StartupObject>Privon.App.Program</StartupObject>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Privon.Browser\Privon.Browser.csproj" />
    <ProjectReference Include="..\Privon.Core\Privon.Core.csproj" />
    <ProjectReference Include="..\Privon.Detection\Privon.Detection.csproj" />
    <ProjectReference Include="..\Privon.Storage\Privon.Storage.csproj" />
    <ProjectReference Include="..\Privon.Windows\Privon.Windows.csproj" />
  </ItemGroup>

</Project>
